[package]
name = "kobo_dict"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
edition = "2018"


[dependencies]
clap = "2"
zip = { git = "https://github.com/cessen/zip", branch = "raw_filename" }
flate2 = "1"
quick-xml = "0.22"
regex = "1.5"